# -*- coding: utf-8 -*-
"""more_visuals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiUccvcQPGO-11zuQCUhywr7yCMGyt7i
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("mal_anime_clean.csv")

df["year"] = pd.to_numeric(df["year"], errors="coerce")
df = df.dropna(subset=["year"])
df["year"] = df["year"].astype(int)

anime_per_year = df["year"].value_counts().sort_index()

plt.figure(figsize=(12, 5))
anime_per_year.plot(kind="bar")

plt.title("Number of Anime Released Per Year")
plt.xlabel("Year")
plt.ylabel("Count")

years = anime_per_year.index
plt.xticks(
    ticks=range(0, len(years), 3),
    labels=years[::3],
    rotation=45
)

plt.tight_layout()
plt.show()

source_counts = df["source"].value_counts().head(10)

plt.figure(figsize=(10, 5))
source_counts.plot(kind="bar")

plt.title("Top Sources of Anime Adaptations")
plt.xlabel("Source Material")
plt.ylabel("Count")

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()