# -*- coding: utf-8 -*-
"""exploratory_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiUccvcQPGO-11zuQCUhywr7yCMGyt7i
"""

import pandas as pd
# Load Data into Dataframe
df = pd.read_csv("mal_anime_clean.csv")

# Print the correlation coefficent for each numerical statistic
print("Correlation Matrix:")
print(df[['rating', 'popularity', 'episodes','year']].corr(), "\n")

#Seperate the rows to catch each genre for each row
df_genres = df.copy()
df_genres['genres'] = df_genres['genres'].str.split(', ')
df_genres = df_genres.explode('genres')

#Print top 10 genres
print("Top Genres:")
print(df_genres['genres'].value_counts().head(10), "\n")

#Print the count of animes by Source
print("Count by Source")
print(df['source'].value_counts(), '\n')

#Print the Average Rating for each Source
print("Average Rating by Source")
print(df.groupby('source')['rating'].mean().sort_values(ascending=False), "\n")

#Print the count of animes by Media
print("Count by Media Type:")
print(df['media_type'].value_counts(), "\n")

#Print the Average Rating for each Media
print("Average Rating by Media Type:")
print(df.groupby('media_type')['rating'].mean().sort_values(ascending=False), "\n")